import { motion } from 'framer-motion';
import { usePageMeta } from '../hooks';

export function TermsPage() {
  usePageMeta({
    title: 'Terms of Service | TheFinCalculator',
    description: 'Terms of Service for TheFinCalculator. Read our terms and conditions for using our financial calculators.',
    url: '/terms',
  });

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white rounded-2xl shadow-sm p-8 md:p-12"
        >
          <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>

          <div className="prose prose-gray max-w-none">
            <p className="text-gray-600 mb-6">
              <strong>Last updated:</strong> February 17, 2026
            </p>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
              <p className="text-gray-600">
                By accessing and using TheFinCalculator website (thefincalculator.com), you agree to be
                bound by these Terms of Service. If you do not agree to these terms, please do not use
                our website. We reserve the right to update these terms at any time, and your continued
                use of the site constitutes acceptance of any changes.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
              <p className="text-gray-600">
                TheFinCalculator provides free online financial calculators and educational content for
                informational purposes. Our tools include investment calculators, loan calculators,
                retirement planners, inflation calculators, and related educational articles. These tools
                are designed to help users make informed financial decisions by providing estimates and
                projections based on user-supplied inputs.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Disclaimer of Financial Advice</h2>
              <p className="text-gray-600 mb-4">
                <strong>TheFinCalculator does not provide financial, investment, tax, or legal advice.</strong>{' '}
                All calculations, projections, and content on this website are for informational and
                educational purposes only. Results generated by our calculators are estimates based on
                the inputs you provide and standard mathematical formulas. They do not account for all
                possible variables that may affect your actual financial outcomes.
              </p>
              <p className="text-gray-600">
                Before making any financial decisions, we strongly recommend consulting with a qualified
                financial advisor, accountant, or other appropriate professional who can consider your
                individual circumstances.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Accuracy of Information</h2>
              <p className="text-gray-600">
                While we strive to provide accurate calculations and up-to-date information, we make no
                warranties or guarantees regarding the accuracy, completeness, or reliability of any
                calculations, content, or information provided on this website. Market conditions, tax
                laws, interest rates, and other financial factors change frequently, and our tools may
                not reflect the most current data. You use the information and calculations at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Intellectual Property</h2>
              <p className="text-gray-600">
                All content on TheFinCalculator, including text, graphics, logos, icons, images, software,
                and the compilation thereof, is the property of TheFinCalculator and is protected by
                copyright and intellectual property laws. You may not reproduce, distribute, modify, or
                create derivative works from any content on this site without our prior written consent.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">6. User Conduct</h2>
              <p className="text-gray-600 mb-4">When using our website, you agree not to:</p>
              <ul className="list-disc pl-6 text-gray-600 space-y-2">
                <li>Use the site for any unlawful purpose or in violation of any applicable laws</li>
                <li>Attempt to interfere with the proper functioning of the website</li>
                <li>Use automated systems or software to extract data from the website (scraping)</li>
                <li>Attempt to gain unauthorized access to any part of the website or its systems</li>
                <li>Transmit any viruses, malware, or other harmful code</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">7. Data Storage</h2>
              <p className="text-gray-600">
                Our calculators allow you to save scenarios using your browser's local storage. This data
                is stored entirely on your device and is not transmitted to our servers. You are responsible
                for managing your locally stored data. We are not responsible for any data loss that may
                occur due to clearing browser data, device failure, or other causes.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">8. Third-Party Content and Advertising</h2>
              <p className="text-gray-600">
                Our website may display advertisements provided by third-party advertising networks,
                including Google AdSense. These advertisements are provided by third parties and are not
                endorsed by TheFinCalculator. We are not responsible for the content, accuracy, or
                practices of any third-party advertiser. Your interactions with advertisers are solely
                between you and the advertiser.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">9. Limitation of Liability</h2>
              <p className="text-gray-600">
                To the fullest extent permitted by law, TheFinCalculator and its owners, operators, and
                contributors shall not be liable for any direct, indirect, incidental, consequential, or
                punitive damages arising from your use of or inability to use this website, including but
                not limited to damages resulting from reliance on any calculation results, information, or
                content provided on this site. Your use of the website is entirely at your own risk.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">10. Indemnification</h2>
              <p className="text-gray-600">
                You agree to indemnify and hold harmless TheFinCalculator, its owners, operators, and
                contributors from any claims, damages, losses, or expenses (including reasonable
                attorney's fees) arising from your use of the website or violation of these Terms of Service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-xl font-semibold text-gray-900 mb-4">11. Changes to Terms</h2>
              <p className="text-gray-600">
                We reserve the right to modify these Terms of Service at any time. Changes will be
                effective immediately upon posting to this page. We will update the "Last updated" date
                at the top of this page to reflect the most recent revision. Your continued use of the
                website after changes are posted constitutes your acceptance of the revised terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-gray-900 mb-4">12. Contact</h2>
              <p className="text-gray-600">
                If you have any questions about these Terms of Service, please contact us through our website.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
